name: tapp
description: A modern, AI-powered Task Management App
version: 0.0.1


environment:
  sdk: '>=1.19.0 <3.0.0'
  flutter: ^0.1.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true